version: "3.9"
services:
  user_db:
    image: mysql:8.0
    container_name: container_user_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: user_db
    ports:
      - "3306:3306"
    volumes:
      - ./database/user_db.sql:/docker-entrypoint-initdb.d/init.sql
      #- user_db_data:/var/lib/mysql
    networks:
      - dsbd_net

  data_db:
    image: mysql:8.0
    container_name: container_data_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: data_db
    ports:
      - "3307:3306"
    volumes:
      - ./database/data_db.sql:/docker-entrypoint-initdb.d/init.sql
      #- data_db_data:/var/lib/mysql
    networks:
      - dsbd_net
    #client:
    #  build: user_manager
    #container_name: container_user

    #server:
    #build: data_collector
    #container_name: container_data
networks:
  dsbd_net:
    driver: bridge

volumes:
  user_db_data:
  data_db_data:
