version: "3.9"
services:

  user_db:
    image: mysql:8.0
    container_name: container_user_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: user_db
    ports:
      - "3306:3306"
    volumes:
      - ./Database/user_db.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD" ]
      interval: 15s
      timeout: 5s
      retries: 10
   # networks:
    #  -userNetwork:

  data_db:
    image: mysql:8.0
    container_name: container_data_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: data_db
    ports:
      - "3307:3306"
    volumes:
      - ./Database/data_db.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 15s
      timeout: 5s
      retries: 10
   # networks:
    #  -dataNetwork:


  #user_manager:
  #  build: user_manager
    #container_name: container_user
  #networks:
    #userNetwork
    #InternalNetwork


  #data_collector:
    #build: data_collector
    #container_name: container_data
    #networks:
      #dataNetwork
      #InternalNetwork

networks:
  dataNetwork:
  userNetwork:
  InternalNetwork:
    driver: bridge
