version: "3.9"
services:
  user_db:
    image: mysql:8.0
    container_name: container_user_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: user_db
    ports:
      - "3311:3306"
    volumes:
      - ./mysql_user:/var/lib/mysql
     # - ./database/user_db.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - user_net
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD" ]
      interval: 10s
      timeout: 5s
      retries: 5

  data_db:
    image: mysql:8.0
    container_name: container_data_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: data_db
    ports:
      - "3307:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
     # - ./database/data_db.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - data_net
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD" ]
      interval: 10s
      timeout: 5s
      retries: 5

  user_manager:
    build: ./user_manager
    container_name: container_user_manager
    ports:
      - "5001:5000"
    environment:
      - DB_HOST=user_db
    depends_on:
      user_db:
        condition: service_healthy
    networks:
      - user_net
      - grpc_net

  data_collector:
     build: ./data_collector
     container_name: container_data_collector
     ports:
       - "5002:5000"
     environment:
       - PYTHONUNBUFFERED=1
       - DB_HOST=data_db
     volumes:
       - ./credentials.json:/app/credentials.json:ro
     depends_on:
       data_db:
         condition: service_healthy
       user_manager:
         condition: service_started
     networks:
       - data_net
       - grpc_net

networks:
  user_net:
    driver: bridge
  data_net:
    driver: bridge
  grpc_net:
    driver: bridge

volumes:
  user_db_data:
  data_db_data:
