version: "3.9"
services:
  user_db:
    image: mysql:8.0
    container_name: container_user_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: user_db
    ports:
      - "3306:3306"
    volumes:
      - user_db_data:/var/lib/mysql

  data_db:
    image: mysql:8.0
    container_name: container_data_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: data_db
    ports:
      - "3307:3306"
    volumes:
      - data_db_data:/var/lib/mysql
    #client:
    #  build: user_manager
    #container_name: container_user

    #server:
    #build: data_collector
    #container_name: container_data

volumes:
  user_db_data:
  data_db_data: