version: "3.9"
services:
  user_db:
    image: mysql:8.0
    container_name: container_user_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${USER_DB_PASSWORD}
      MYSQL_DATABASE: ${USER_DB_NAME}
    ports:
      - "3311:3306"
    volumes:
      - ./mysql_user:/var/lib/mysql
    networks:
      - user_net
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD" ]
      interval: 10s
      timeout: 5s
      retries: 5

  data_db:
    image: mysql:8.0
    container_name: container_data_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DATA_DB_PASSWORD}
      MYSQL_DATABASE: ${DATA_DB_NAME}
    ports:
      - "3307:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
    networks:
      - data_net
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD" ]
      interval: 10s
      timeout: 5s
      retries: 5

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: broker_kafka
    restart: always
    ports:
      - "29092:29092"
    environment:
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: 1
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk
      KAFKA_CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@broker_kafka:29093
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:29092,CONTROLLER://0.0.0.0:29093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker_kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_LOG_DIRS: /var/lib/kafka/data
    volumes:
      - kafka_data:/var/lib/kafka/data
    networks:
      - kafka_net
    healthcheck:
      test: kafka-broker-api-versions --bootstrap-server localhost:9092 || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  alert_system:
    build: ./alert_system
    container_name: alert_system
    restart: always
    depends_on:
      kafka:
        condition: service_healthy
    environment:
      KAFKA_BOOTSTRAP_SERVERS: broker_kafka:9092
    networks:
      - kafka_net

  notifier_system:
    build: ./notifier_system
    container_name: notifier_system
    restart: always
    depends_on:
      kafka:
        condition: service_healthy
    environment:
      KAFKA_BOOTSTRAP_SERVERS: broker_kafka:9092
      SMTP_HOST: smtp.gmail.com
      SMTP_PORT: 587
      SMTP_USER: ${GMAIL_USER}
      SMTP_PASSWORD: ${GMAIL_APP_PASSWORD}
      SENDER_NAME:  BigData notifier system
    networks:
      - kafka_net

  apigw:
    image: nginx:stable
    container_name: my_nginx
    restart: always
    ports:
      - "8443:443"
    depends_on:
      - user_manager
      - data_collector
    volumes:
      - ./nginx/configs/routing.conf:/etc/nginx/conf.d/routing.conf:ro
      - ./nginx/html_content:/usr/share/nginx/html:ro
      - ./nginx/SSL_certificate/nginx-selfsigned.crt:/etc/nginx/ssl/nginx-selfsigned.crt:ro
      - ./nginx/SSL_certificate/nginx-selfsigned.key:/etc/nginx/ssl/nginx-selfsigned.key:ro
    networks:
      - gateway_net

  user_manager:
    build: ./user_manager
    container_name: container_user_manager
    restart: always
    ports:
      - "5001:5000"
    environment:
      - DB_HOST=${USER_DB_HOST}
      - DB_USER=${USER_DB_USER}
      - DB_PASSWORD=${USER_DB_PASSWORD}
      - DB_NAME=${USER_DB_NAME}
    depends_on:
      user_db:
        condition: service_healthy
    networks:
      - user_net
      - grpc_net
      - gateway_net

  data_collector:
     build: ./data_collector
     container_name: container_data_collector
     restart: always
     ports:
       - "5002:5000"
     environment:
       - PYTHONUNBUFFERED=1
       - DB_HOST=${DATA_DB_HOST}
       - DB_USER=${DATA_DB_USER}
       - DB_PASSWORD=${DATA_DB_PASSWORD}
       - DB_NAME=${DATA_DB_NAME}
       - OPENSKY_CLIENT_ID=${OPENSKY_CLIENT_ID}
       - OPENSKY_CLIENT_SECRET=${OPENSKY_CLIENT_SECRET}
       - KAFKA_BOOTSTRAP_SERVERS=broker_kafka:9092
     depends_on:
       data_db:
         condition: service_healthy
       user_manager:
         condition: service_started
       kafka:
         condition: service_healthy
     networks:
       - data_net
       - grpc_net
       - gateway_net
       - kafka_net


networks:
  user_net:
  data_net:
  grpc_net:
    driver: bridge
  gateway_net:
  kafka_net:

volumes:
  user_db_data:
  data_db_data:
  kafka_data: